package app.orb;


/**
* a2/orb/RetailStoreOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/Misha/workspace/423/drs.idl
* Sunday, November 4, 2012 8:25:00 PM EST
*/

public interface RetailStoreOperations 
{
  void purchaseItem (String customerID, int itemID, int numberOfItem) throws app.orb.RetailStorePackage.NoSuchItem, app.orb.RetailStorePackage.InsufficientQuantity;
  void returnItem (String customerID, int itemID, int numberOfItem) throws app.orb.RetailStorePackage.InvalidReturn;
  boolean transferItem (int itemID, int numberOfItem);
  String checkStock (int itemID);
  void exchange (String customerID, int boughtItemID, int boughtNumber, int desiredItemID, int desiredNumber) throws app.orb.RetailStorePackage.InvalidReturn, app.orb.RetailStorePackage.NoSuchItem, app.orb.RetailStorePackage.InsufficientQuantity;
} // interface RetailStoreOperations
