package app.orb;


/**
* a2/orb/RetailStorePOATie.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/Misha/workspace/423/drs.idl
* Sunday, November 4, 2012 8:25:00 PM EST
*/

public class RetailStorePOATie extends RetailStorePOA
{

  // Constructors

  public RetailStorePOATie ( app.orb.RetailStoreOperations delegate ) {
      this._impl = delegate;
  }
  public RetailStorePOATie ( app.orb.RetailStoreOperations delegate , org.omg.PortableServer.POA poa ) {
      this._impl = delegate;
      this._poa      = poa;
  }
  public app.orb.RetailStoreOperations _delegate() {
      return this._impl;
  }
  public void _delegate (app.orb.RetailStoreOperations delegate ) {
      this._impl = delegate;
  }
  public org.omg.PortableServer.POA _default_POA() {
      if(_poa != null) {
          return _poa;
      }
      else {
          return super._default_POA();
      }
  }
  public void purchaseItem (String customerID, int itemID, int numberOfItem) throws app.orb.RetailStorePackage.NoSuchItem, app.orb.RetailStorePackage.InsufficientQuantity
  {
    _impl.purchaseItem(customerID, itemID, numberOfItem);
  } // purchaseItem

  public void returnItem (String customerID, int itemID, int numberOfItem) throws app.orb.RetailStorePackage.InvalidReturn
  {
    _impl.returnItem(customerID, itemID, numberOfItem);
  } // returnItem

  public boolean transferItem (int itemID, int numberOfItem)
  {
    return _impl.transferItem(itemID, numberOfItem);
  } // transferItem

  public String checkStock (int itemID)
  {
    return _impl.checkStock(itemID);
  } // checkStock

  public void exchange (String customerID, int boughtItemID, int boughtNumber, int desiredItemID, int desiredNumber) throws app.orb.RetailStorePackage.InvalidReturn, app.orb.RetailStorePackage.NoSuchItem, app.orb.RetailStorePackage.InsufficientQuantity
  {
    _impl.exchange(customerID, boughtItemID, boughtNumber, desiredItemID, desiredNumber);
  } // exchange

  private app.orb.RetailStoreOperations _impl;
  private org.omg.PortableServer.POA _poa;

} // class RetailStorePOATie
