package app.orb;


/**
* a2/orb/RetailStoreHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/Misha/workspace/423/drs.idl
* Sunday, November 4, 2012 8:25:00 PM EST
*/

abstract public class RetailStoreHelper
{
  private static String  _id = "IDL:a2/orb/RetailStore:1.0";

  public static void insert (org.omg.CORBA.Any a, app.orb.RetailStore that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static app.orb.RetailStore extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (app.orb.RetailStoreHelper.id (), "RetailStore");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static app.orb.RetailStore read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_RetailStoreStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, app.orb.RetailStore value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static app.orb.RetailStore narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof app.orb.RetailStore)
      return (app.orb.RetailStore)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      app.orb._RetailStoreStub stub = new app.orb._RetailStoreStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static app.orb.RetailStore unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof app.orb.RetailStore)
      return (app.orb.RetailStore)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      app.orb._RetailStoreStub stub = new app.orb._RetailStoreStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
