package app.client;
/*
 * The client implementation is generated by the ORB Studio.
 */

import java.io.IOException;
import java.util.Properties;
import org.omg.CORBA.ORBPackage.InvalidName;
import org.omg.CosNaming.NamingContextExt;
import org.omg.CosNaming.NamingContextExtHelper;
import org.omg.CosNaming.NamingContextPackage.CannotProceed;
import org.omg.CosNaming.NamingContextPackage.NotFound;

import app.orb.RetailStorePackage.InsufficientQuantity;
import app.orb.RetailStorePackage.InvalidReturn;
import app.orb.RetailStorePackage.NoSuchItem;

public class RetailStoreClientImpl implements Runnable {
	private final int INVENTORY_SIZE = 10;
	private final int ITEM_ID_OFFSET = 1000;
	private final int PURCHASE_QUANTITY = 2;
	private final int RETURN_QUANTITY = 2;
	
	private String customerID;
	private app.orb.RetailStore store = null;
	private org.omg.CORBA.ORB orb = null;

	/**
	 * Constructor for RetailStoreClientImpl
	 * 
	 * @throws IOException
	 */
	public RetailStoreClientImpl(String customerID, boolean checkStock) throws IOException {
		this(customerID, null);
	}

	/**
	 * Constructor for RetailStoreClientImpl
	 * 
	 * @throws IOException
	 * @see java.lang.Object#Object()
	 */
	public RetailStoreClientImpl(String customerID, String[] args) throws IOException {
		this.customerID = customerID;
		String storeCode = customerID.toCharArray()[0] + ""; // cast to String
		
		initORB(storeCode, args);
	}
	
	public void purchaseItem(int itemID, int numberOfItem) throws NoSuchItem, InsufficientQuantity {
		store.purchaseItem(customerID, itemID, numberOfItem);
	}
	
	public void returnItem(int itemID, int numberOfItem) throws InvalidReturn {
		store.returnItem(customerID, itemID, numberOfItem);
	}
	
	public String checkStock(int itemID) {
		return store.checkStock(itemID);
	}
	
	public void exchange(int boughtItemID, int boughtNumber,
			int desiredItemID, int desiredNumber) throws InvalidReturn, NoSuchItem, InsufficientQuantity {
		store.exchange(customerID, boughtItemID, boughtNumber, desiredItemID, desiredNumber);
	}

	/**
	 * Initialize ORB.
	 *  
	 * @param args
	 * @throws IOException
	 */
	private void initORB(String storeCode, String[] args) throws IOException {

		Properties props = System.getProperties();
		props.setProperty("org.omg.CORBA.ORBClass", "com.sun.corba.se.internal.POA.POAORB");
		props.setProperty("org.omg.CORBA.ORBSingletonClass", "com.sun.corba.se.internal.corba.ORBSingleton");
		props.setProperty("org.omg.CORBA.ORBInitialPort", "1050");
        props.setProperty("org.omg.CORBA.ORBInitialHost", "Misha-PC");

		// Initialize the ORB
		orb = org.omg.CORBA.ORB.init((String[])args, props);

		// ---- Uncomment below to enable Naming Service access. ----
		org.omg.CORBA.Object ncobj = null;
		try {
			ncobj = orb.resolve_initial_references("NameService");
		} catch (InvalidName e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		
		NamingContextExt nc = NamingContextExtHelper.narrow(ncobj);
		org.omg.CORBA.Object obj = null;
		try {
			obj = nc.resolve_str(storeCode);
		} catch (NotFound e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} catch (CannotProceed e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} catch (org.omg.CosNaming.NamingContextPackage.InvalidName e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}

		store = app.orb.RetailStoreHelper.narrow(obj);		
	}

	/**
	 * Shutdown ORB.
	 */
	public void shutdown() {
		orb.shutdown(true);
	}

	/**
	 * Test driver for RetailStoreClientImpl.
	 */
	public void run() {
		for (int i = 0; i < INVENTORY_SIZE; i++) {
			try {
				// check the stock
				System.out.println(checkStock(ITEM_ID_OFFSET + i));
				// try to purchase the item
				purchaseItem(ITEM_ID_OFFSET + i, PURCHASE_QUANTITY);
			} catch (NoSuchItem e) {
				System.err.println(customerID + ": Item with ID " +  (ITEM_ID_OFFSET + i) + " does not exist!");
			} catch (InsufficientQuantity e) {
				System.err.println(customerID + ": There is not enough stock to fulfill your order!");
			} catch (Exception e) {
			    System.err.println("Purchase exception: " + e.toString());
			    e.printStackTrace();
			}
			System.out.println(customerID +  ": Successfully purchased " + PURCHASE_QUANTITY + " of item " + (ITEM_ID_OFFSET + i) + ".");
		}
		for (int i = INVENTORY_SIZE - 1; i >= 0; i--) {
			try {
				// check the stock
				System.out.println(checkStock(ITEM_ID_OFFSET + i));
				// try to return the item
				returnItem(ITEM_ID_OFFSET + i, RETURN_QUANTITY);
			} catch (InvalidReturn e) {
				System.err.println(customerID + ": Warning! You attempted to return more than you purchased.");
			} catch (Exception e) {
			    System.err.println("Return exception: " + e.toString());
			    e.printStackTrace();
			}
			System.out.println(customerID +  ": Successfully returned " + RETURN_QUANTITY + " of item " + (ITEM_ID_OFFSET + i) + ".");
		}
		try {
			// try to purchase an item
			purchaseItem(1002, PURCHASE_QUANTITY);
			System.out.println(customerID +  ": Successfully purchased " + PURCHASE_QUANTITY + " of item 1002.");
			// try to exchange the item
			exchange(1002, PURCHASE_QUANTITY, 1008, PURCHASE_QUANTITY);
		} catch (NoSuchItem e) {
			System.err.println(customerID + ": Item with ID 1008 does not exist!");
		} catch (InsufficientQuantity e) {
			System.err.println(customerID + ": There is not enough stock to fulfill your order!");
		} catch (InvalidReturn e) {
			System.err.println(customerID + ": Warning! You attempted to return more than you purchased.");
		} catch (Exception e) {
		    System.err.println("Return exception: " + e.toString());
		    e.printStackTrace();
		}
		System.out.println(customerID +  ": Successfully exchanged " + PURCHASE_QUANTITY + " of item 1002 for " +
				PURCHASE_QUANTITY + " of item 1008.");
		shutdown();
	}
}
