package app.orb.RetailStorePackage;

/**
* a2/orb/RetailStorePackage/InsufficientQuantityHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/Misha/workspace/423/drs.idl
* Sunday, November 4, 2012 8:25:00 PM EST
*/

public final class InsufficientQuantityHolder implements org.omg.CORBA.portable.Streamable
{
  public app.orb.RetailStorePackage.InsufficientQuantity value = null;

  public InsufficientQuantityHolder ()
  {
  }

  public InsufficientQuantityHolder (app.orb.RetailStorePackage.InsufficientQuantity initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = app.orb.RetailStorePackage.InsufficientQuantityHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    app.orb.RetailStorePackage.InsufficientQuantityHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return app.orb.RetailStorePackage.InsufficientQuantityHelper.type ();
  }

}
