package app.orb.RetailStorePackage;

/**
* a2/orb/RetailStorePackage/InvalidReturnHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/Misha/workspace/423/drs.idl
* Sunday, November 4, 2012 8:25:00 PM EST
*/

public final class InvalidReturnHolder implements org.omg.CORBA.portable.Streamable
{
  public app.orb.RetailStorePackage.InvalidReturn value = null;

  public InvalidReturnHolder ()
  {
  }

  public InvalidReturnHolder (app.orb.RetailStorePackage.InvalidReturn initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = app.orb.RetailStorePackage.InvalidReturnHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    app.orb.RetailStorePackage.InvalidReturnHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return app.orb.RetailStorePackage.InvalidReturnHelper.type ();
  }

}
